In [ ]:
#do extension matter when creating a library

In [4]:
import numpy as np

In [7]:
a = [1.2,4,5,6,7,99]
a = np.array(a,dtype = int)

In [8]:
a

array([ 1,  4,  5,  6,  7, 99])

In [9]:
#for range write arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
a.size

6

In [21]:
len(a)

6

In [22]:
a.shape

(6,)

In [23]:
a.dtype

dtype('int64')

In [36]:
np.random.randint(1,1000, size = (2,3,4,5,6,7,8,9), dtype = np.int16)

array([[[[[[[[470, 340, 486, ..., 209, 654, 328],
             [193, 478, 788, ..., 662, 804, 801],
             [560,  14, 767, ..., 693, 264, 202],
             ...,
             [123, 500, 852, ..., 891, 992, 151],
             [730, 111,  94, ...,  88, 750, 805],
             [576, 789, 670, ..., 968, 866, 155]],

            [[653, 579, 356, ..., 302,  18, 872],
             [126, 704, 308, ..., 603, 123, 410],
             [625, 825, 731, ..., 740, 330, 871],
             ...,
             [204, 686,  88, ..., 124, 802, 402],
             [639, 831, 860, ..., 933, 857, 642],
             [426,   5, 328, ..., 445, 381, 426]],

            [[803, 213, 548, ..., 283, 700, 418],
             [580, 147, 586, ..., 853, 117, 527],
             [996, 795, 899, ..., 526, 984, 859],
             ...,
             [391,  45, 445, ..., 945, 553,  48],
             [221, 168, 564, ..., 177, 258, 815],
             [479, 795, 323, ..., 787, 267, 393]],

            ...,

            [[964,  80

In [43]:
i = np.random.randint(1,1000, size = (3,3), dtype = np.int16)

In [44]:
np.random.choice(["Head","Tail"],size = 10)

array(['Head', 'Tail', 'Head', 'Head', 'Head', 'Head', 'Head', 'Tail',
       'Tail', 'Tail'], dtype='<U4')

In [45]:
print(i)

[[143 444 728]
 [976 610 398]
 [150 761 205]]


In [46]:
i[1,2]
#i.item(1)

np.int16(398)

In [52]:
#Slicing

i[:2,::-1]

array([[728, 444, 143],
       [398, 610, 976]], dtype=int16)

In [53]:
i[:2,::-2]

array([[728, 143],
       [398, 976]], dtype=int16)

In [58]:
i[(i%2 == 0) & (i > 600)]

array([728, 976, 610], dtype=int16)

In [57]:
i[i%2 == 1]

array([143, 761, 205], dtype=int16)

In [63]:
two = np.random.choice([1,2,3,4],size = (10,10))

In [64]:
np.unique(two)

array([1, 2, 3, 4])

In [65]:
np.unique_counts(two)

UniqueCountsResult(values=array([1, 2, 3, 4]), counts=array([24, 32, 25, 19]))

In [66]:
two.reshape(2,50)

array([[1, 1, 2, 2, 2, 1, 2, 4, 1, 2, 3, 2, 2, 4, 4, 3, 2, 2, 1, 1, 1, 4,
        4, 4, 1, 4, 2, 1, 2, 3, 4, 2, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 4, 3,
        4, 1, 3, 3, 3, 2],
       [1, 1, 1, 2, 4, 4, 2, 2, 2, 2, 4, 1, 1, 2, 1, 2, 1, 3, 4, 2, 3, 2,
        2, 2, 4, 1, 2, 3, 3, 3, 3, 4, 3, 3, 2, 2, 3, 1, 4, 3, 3, 3, 3, 1,
        3, 4, 2, 2, 3, 2]])